config/routes.rb
Rails.application.routes.draw do
  root 'pages#root'
  get '/my_page' => 'pages#show', as: 'profile'
  get '/friendship' => 'pages#friendship'
  get '/accept' => 'pages#accept', as: 'accept'
  get '/decline' => 'pages#decline', as: 'decline'
  put "like", to: "pages#like"
  put "dislike", to: "pages#dislike"
  devise_for :users

  resources :images do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_many :comments
  acts_as_votable

  has_attached_file :photo,
                    styles: { large: '500x500', medium: '300x300', thumb: '100x100'},
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :photo, 
                    content_type: ['image/jpeg', 'image/gif', 'image/png']
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, presence: true, length: {maximum: 50}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
  has_friendship
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permited_parameters, if: :devise_controller?

  private

  def configure_permited_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    params.permit!
    @image_id = params[:image_id]
    @image = Image.find(params[:image_id])
    @comment = @image.comments.create(params[:comment])

    respond_to do |format|
      format.html {redirect_to root_path}
      format.js {}
    end
  end

  def destroy
    @image = Image.find(params[:image_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      # format.html { redirect_to @article }
      format.json { head :no_content }
      format.js   {}
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
  	@image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user

    if @image.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to profile_path
  end

  private

  def image_params
  	params.require(:image).permit(:description, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :block
  def root
    @pics = []
    current_user.friends.each do |f|
      f.images.each do |img|
        @pics.push(img)
      end
    end
    unless @pics == nil
      @pics = @pics.sort! { |a,b| b.id <=> a.id }
    end
  end

  def show
  	@images = current_user.images.order(id: :desc)
  end

  def friendship
  	@frnd = User.find(params[:q])
  	current_user.friend_request(@frnd)

  	redirect_to profile_path
  end

  def accept
    @frnd = User.find(params[:format])
    current_user.accept_request(@frnd)

    redirect_to profile_path
  end

  def decline
    @frnd = User.find(params[:format])
    current_user.decline_request(@frnd)

    redirect_to profile_path
  end

  def like
    @img = Image.find(params[:format])
    @img.liked_by current_user
    redirect_to root_path
  end

  private

  def block
    if current_user == nil
      flash[:danger] = "Please log in"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.erb
<li>
  <p>
    <%= comment.image.user.name %>: <%= comment.description %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [comment.image, comment], method: :delete, class: "comment-delete", remote: true %>
  </p>
</li>

app/views/comments/_form.erb
<%= form_for [@pic, @pic.comments.build], remote: true do |f| %>
    <% f.hidden_field :user, :value => current_user %>
    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/comments/create.js.erb
$("#comments<%= @image_id %>").append("<%= j render @comment %>");
$("#comment_commenter").val("");
$("#comment_body").val("");
addDeletelClickEvent()

app/views/comments/destroy.js.erb
$(".comment-delete").on("ajax:success", function(){
	$(this).parents("li").remove();
})

app/views/images/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Image</h1>
  </div>
</div>
<hr />

<%= form_for @image, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @image.errors[:description].any? %>">
      <%= f.label :description, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control' %>
        <%= render 'shared/field_errors', object: @image, field_name: :description %>
      </div>
    </div>

    <div class="form-group <%= 'has-error' if @image.errors[:photo].any? %>">
      <%= f.label :photo, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.file_field :photo, id: "pictureInput" %>
        <br>
        <div id="target">
        </div>
        <%= render 'shared/field_errors', object: @image, field_name: :photo %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

<script>
  $(function() {
  $('#pictureInput').on('change', function(event) {
    var files = event.target.files;
    var image = files[0]
    var reader = new FileReader();
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      img.src = file.target.result;
      $('#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/application/navbar' %>
<div class="container">
  <br>
  <br>
  <br>
  <% if user_signed_in? %>
    <div class="row">
      <%= link_to "Add Image", new_image_path, class: "btn btn-success" %>
    </div>
  <% end %>
  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>
  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Instaagram2', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Feed", root_path %></li>
        <li><%= link_to "My Profile", profile_path %></li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <p class="navbar-text">
            Logged in as <%= current_user.name %>
          </p>
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/pages/root.html.erb
<br><br>
<% unless @pics == nil %>
  <% @pics.each do |pic| %>
    <% @pic = pic %>
    <div class="row">
      <div class="col-md-6 btn btn-default">
        <%= image_tag pic.photo.url(:large) %><br>
      </div>
      <div class="col-md-6">
      <br>
        <h3><b>By:</b> <%= pic.user.name %><br></h3>
        <h3><b>Description:</b> <%= pic.description %><br></h3>
        <h3><b>Comments:</b><br></h3>
        <section id="comment-section">
          <ol id="comments<%= pic.id %>">
            <%= render pic.comments %>
          </ol>

          <h4>Add a comment:</h4>

          <%= render 'comments/form' %>

        </section>
        <% unless current_user.liked? @pic %>
          <%= link_to "Like | #{@pic.get_likes.size}", like_path(@pic), class: 'btn btn-success', method: :put %>
        <% else %>
          <%= link_to "Liked | #{@pic.get_likes.size}", "#", class: 'btn btn-default' %>
        <% end %>
      </div>
      <br>
      <br>
    </div>
  <% end %>
<% end %>

app/views/pages/show.html.erb
<div class="row">
  <div class="col-sm-5">
    <h1><%= current_user.name %></h1>
    <h6>Your id: <%= current_user.id %> (is used to add you to smb's friends list)</h6>
    <%= form_tag("/friendship", method: "get") do %>
      <%= label_tag(:q, "Add a friend:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Add")  %>
    <% end %>
  </div>
  <div class="col-sm-7">
    <br>
    <h3>Your friends:</h3>
    <% current_user.friends.each do |frnd| %>
      <h4><%= frnd.name %></h4>
      <br>
    <% end %>
    <br>
  </div>
</div>
<% if current_user.pending_friends.any? %>
  <div class="row">
    <h3>Guys you have sent friend requests to:</h3>
    <div class="col-sm-5">
      <% current_user.pending_friends.each do |frnd| %>
        <%= frnd.name %>
        <br>
      <% end %>
      <br>
    </div>
  </div>
<% end %>
<% if current_user.requested_friends.any? %>
  <div class="row">
  <h3>Guys you have recieved friend requests from:</h3>
    <div class="col-sm-5">
      <% current_user.requested_friends.each do |frnd| %>
        <%= frnd.name %>
        <%= link_to 'Accept', accept_path(frnd), class: 'btn btn-success' %>
        <%= link_to 'Decline', decline_path(frnd), class: 'btn btn-danger' %>
        <br>
      <% end %>
      <br>
    </div>
  </div>
<% end %>
<br><br>
<table>
  <% @images.each_slice(2) do |images| %>
    <tr>
      <% images.each do |pic| %>
        <% @pic = pic %>
        <td class="btn btn-default">
          <div class="row">
            <div class="col-md-8">
              <%= image_tag pic.photo.url(:large) %><br>
              <b>Description:</b> <%= pic.description %><br>
              <%= link_to 'Delete', image_path(pic.id), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default' %>
            </div>
            <div class="col-md-4">
              <section id="comment-section">
                <ol id="comments<%= pic.id %>">
                  <%= render pic.comments %>
                </ol>

                <h4>Add a comment:</h4>

                <%= render 'comments/form' %>

              </section>
              <%= link_to "Liked | #{@pic.get_likes.size}", "#", class: 'btn btn-default' %>
            </div>
          </div>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/shared/_field_errors.html.erb
<% if object.errors[field_name].any? %>
    <ul class="error-messages">
      <% object.errors.full_messages_for(field_name).each do |error| %>
          <li><%= error %></li>
      <% end %>
    </ul>
<% end %>